---
title: "FIFA_midstone_project"
output: html_notebook
---



```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
library(ggpubr)
library(ggthemes)
library(gganimate)
library(scales)
#install.packages("highcharter")
library(highcharter)
library(kableExtra)

```

```{r}
#bring in the la_liga table dataset 
la_liga_table <- read_csv('data/la_liga_table.csv')
```


```{r}
glimpse(la_liga_table)

```


```{r}
str(la_liga_table)

```


```{r}
dim(la_liga_table)
```


```{r}
summary(la_liga_table)

```


```{r}
winner <- la_liga_table %>%
  group_by(season) %>% 
  top_n(1, points) %>% 
  select(club, points)
  
winner <-winner[-c(38), ]

```


```{r}
```


```{r}
champions <- winner %>% 
  group_by(club) %>% 
  count() %>% 
  rename(champ = n) %>% 
  arrange(desc(champ)) %>% 
  ungroup()
```


```{r}
```


```{r}
## set the levels in order we want
# champions <- within(champions,
#                     champions <- factor(champions,
#                                         levels= names(sort(table(champions),
#                                                            decreasing =TRUE))))
# 

```

```{r}
ggplot(champions, aes(x = reorder(club, -champ), y =champ))+
  geom_bar(stat='identity',color='black',fill='steelblue')+
  geom_text(aes(y = champ +1, label = champ ))

```

```{r}

total_results <- la_liga_table %>% 
  group_by(club) %>% 
  summarise(
    `total games` = sum(total_matches),
    wins = sum(matches_won),
    losses = sum(matches_lost),
    draws = sum(matches_drawn)
  ) %>% 
  arrange(desc(`total games`),desc(wins),desc(losses)) %>% 
  ungroup() 

total_results


```
```{r}
#pivot the data 
total_results <- total_results %>% 
  pivot_longer(`total games`:draws, names_to ='games',
               values_to ='number') %>%
  filter(club =='Real Madrid'| club == 'FC Barcelona'| club == 'Atlético Madrid' | club == 'Valencia CF' | club == 'Athletic Club de Bilbao' | club == ' Real Sociedad' | club == 'Deportivo Alavés' | club ==  'RCD Espanyol' | club == 'Sevilla FC' | club == 'Real Zaragoza'| club == 'Real Betis' | club == 'Real Sporting de Gijón' | club == 'RC Celta' | club == 'CA Osasuna' | club == 'Real Valladolid CF')
  
  
  

total_results
```


```{r}
#grouped bar chart
# A few explanation about the code below:
# 
# input dataset must provide 3 columns: the numeric value (value), and 2 categorical variables for the group (specie) and the subgroup (condition) levels.
# in the aes() call, x is the group (specie), and the subgroup (condition) is given to the fill argument.
# in the geom_bar() call, position="dodge" must be specified to have the bars one beside each other.

ggplot(total_results, aes(x = club, y = number, fill = games))+
  geom_col(position = 'dodge')+
  theme(axis.text.x = element_text(angle = 90))

```


```{r}
win_loss_total <- la_liga_table %>% 
  select(season, club, home_win, away_win, home_loss, away_loss) %>% 
  group_by(club) %>% 
  summarize(
    `home win` = sum(home_win),
    `away win` = sum(away_win),
    `home loss` = sum(home_loss),
    `away loss` = sum(away_loss)
  ) %>% 
  ungroup()

win_loss_total

```


```{r}
win_loss_total <- win_loss_total %>% 
  pivot_longer(`home win`:`away win`, names_to = 'win',
               values_to = 'wins') %>% 
  pivot_longer(`home loss`:`away loss`,names_to = 'loss',
               values_to = 'losses')
win_loss_total

```


```{r}
ggplot(win_loss_total, aes(x = club, y = wins, fill = win))+
  geom_col(position = 'dodge')+
  ggtitle('Total home and away wins')+
  xlab('')+
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
ggplot(win_loss_total, aes(x = club, y = losses, fill = loss))+
  geom_col(position = 'dodge')+
  ggtitle('Total home and away losses')+
  xlab('')+
  theme(axis.text.x = element_text(angle = 90))
  

```


```{r}
goals <- la_liga_table %>% 
  select(season, club, home_goals, away_goals, goals_scored, goals_conceded, goal_difference) %>% 
  group_by(club) %>% 
  summarize(
    home_goals = sum(home_goals),
    away_goals = sum(away_goals),
    total_goals_scored = sum(goals_scored),
    goals_conceded = sum(goals_conceded),
    goal_difference = sum(goal_difference)
  ) %>% 
  ungroup()

goals

```


```{r}
#total goals scored
goals %>% 
  mutate(club = fct_reorder(club,total_goals_scored)) %>% 
  ggplot(aes(x = club, y = total_goals_scored))+
  geom_col(fill='purple', width = .5)+
  coord_flip()





```

```{r}
#total goals conceded
goals %>% 
  mutate(club = fct_reorder(club,goals_conceded)) %>% 
  ggplot(aes(x = club, y = goals_conceded))+
  geom_col(fill="darkblue",alpha = .8, width = .5)+
  theme(axis.text.x = element_text(angle = 90))

```

```{r}


```


```{r}

```


```{r}
win_vs_goals <- la_liga_table %>% 
  select(season, club,matches_won, matches_lost,goals_scored, goals_conceded,goal_difference) %>% 
  group_by(club) %>% 
  summarize(
    won = sum(matches_won),
    lost = sum(matches_lost),
    goals_scored = sum(goals_scored),
    goals_conceded = sum(goals_conceded),
    goal_diff = sum(goal_difference)
  ) %>% 
  ungroup()

win_vs_goals
```

```{r}

```

```{r}
# A scatter plot of goals scored vs games won
ggplot(win_vs_goals, aes(x=won, y=goals_scored, color= club)) + 
    geom_point()+
  theme(
    legend.position = "none"
  )+
  geom_label(
    data = win_vs_goals %>%filter(won>500 & goals_scored >2000),aes(label = club)
  )





```


```{r}
#goals scored vs games won
ggscatter(win_vs_goals, x= 'won', y='goals_scored',
          add= 'reg.line',conf.int=TRUE,
          cor.coef=TRUE, cor.method= 'pearson',
          xlab='total wins', ylab= 'total goals scored')+
  theme(legend.position='none')

```


```{r}
# A scatter plot of goals conceded vs games won
ggplot(win_vs_goals, aes(x=won, y=goals_conceded, color= club)) + 
    geom_point()+
  theme(
    legend.position = "none"
  )+
  geom_label(
    data = win_vs_goals %>%filter(won>500 & goals_scored >2000),aes(label = club)
  )
```


```{r}
#goals allowed vs games won
ggscatter(win_vs_goals, x= 'won', y='goals_conceded',
          add= 'reg.line',conf.int=TRUE,
          cor.coef=TRUE, cor.method= 'pearson',
          xlab='total wins', ylab= 'total goals allowed')+
  theme(legend.position='none')
```


```{r}
 ggplot(win_vs_goals,aes(x=won, y=goal_diff, color = club))+
  geom_point()+
  theme(
    legend.position = "none"
  )+
  geom_label(
    data = win_vs_goals %>%  filter(won>500 & goal_diff >10),aes(label=club)
  )
  
```


```{r}

 
ggscatter(win_vs_goals,x= 'won',y='goal_diff',
          add= 'reg.line',conf.int=TRUE,
          cor.coef=TRUE, cor.method= 'pearson',
          xlab='total wins', ylab= 'total goals allowed')+
  theme(legend.position='none')
```
```{r}
#bring in the la_liga table dataset 
player_data <- read_csv('data/fifa_player_data_07-17.csv') %>% 
  rename(season = Year, club = Club)
```
```{r}
dim(player_data)
```


```{r}
#filter table to 2007 and up
table_07_up <- la_liga_table %>% 
  filter(season >= 2007)
#merge the data by club and season/year

player_n_laliga_table <- table_07_up %>% 
  inner_join(player_data, by= c('club', 'season'))

dim(player_n_laliga_table)

```
```{r}
player_n_laliga_table %>% 
  select(season) %>% 
  unique()
```


```{r}

```

```{r}
#champions from 2007 to 2017
champ_07 <-player_n_laliga_table %>% 
  group_by(season) %>% 
  top_n(1, points) %>% 
  select(club, points) %>% 
  unique()

champ_07 <-champ_07[-2, ]

champ_07 <- champ_07 %>% 
  group_by(club) %>% 
  count() %>% 
  rename(trophies = n) %>% 
  arrange(desc(trophies)) %>% 
  ungroup()

champ_07

```

```{r}
#winners from 2007 to 2017
ggplot(champ_07, aes(x = reorder(club, -trophies), y =trophies))+
  geom_bar(stat='identity',color='black',fill='red')+
  geom_text(aes(y = trophies +.2, label = trophies ))

```


```{r}
player_n_laliga_table 
```


```{r}
#distribution of age over the 11 seasons
ggplot(player_n_laliga_table, aes(x = Age))+
  geom_histogram(bins=25)+
  facet_wrap(~season)

```
```{r}
#distribution of age over the 11 seasons
ggplot(player_n_laliga_table, aes(x = Age))+
  geom_histogram(bins=25)+
  facet_grid(Position~season)
```


```{r}
#library(ggthemes)
player_n_laliga_table %>%
  group_by(season,Age) %>% 
  summarise(Rating = mean(Overall)) %>% 
  ggplot(aes(x = Age, y = Rating, group = 1))+
  geom_line(color = 'red', size = 1)+
  ggtitle('The Age Curve Flattens Off', subtitle = 'player ratings tend not to get better after the age of 30')+
  xlab('Age')+
  theme_fivethirtyeight()+
  theme(axis.title = element_text(), axis.title.y = element_blank(), axis.title.x = element_text(face = 'bold'))+
  facet_wrap(~season)

```


```{r}
#age vs rating per year per position
player_n_laliga_table %>% 
  group_by(season, Position, Age) %>% 
  summarise(Rating = mean(Overall)) %>% 
  ggplot(aes(x = Age, y = Rating, group = Position,color = Position))+
  geom_line(size = 1)+
  theme_fivethirtyeight()+
  facet_grid(Position ~season, scales = "free_y")+
  theme(strip.background = element_rect (fill = 'darkgreen'), strip.text = element_text(colour = 'white', face = 'bold'))
  
#facet_grid(vs ~ carb)
```


```{r}
player_n_laliga_table %>% 
  filter(season == 2016) %>% 
  ggplot(aes(x = Position, y= Value_spread))+
  geom_boxplot(fill= 'darkgrey')+
  scale_y_log10(labels= dollar_format(prefix = "$"))+
  ggtitle('Positions to Break the Transfer market in 2016', subtitle = 'Attackers and midfielders bring the fans to games...\nPay them the money!')+
  theme_fivethirtyeight()

```

```{r}
player_n_laliga_table %>% 
  mutate(agebox = ifelse(Age <= 20, '20 and under', ifelse(Age >20 & Age <=25, '21 to 25', ifelse(Age >25 & Age <=30, '25 to 30', ifelse(Age >30 & Age <=35, '31 to 35', 'Over 35')))))%>% 
  ggplot(aes(x = agebox, y = Value_spread))+
  geom_boxplot(fill = 'darkgrey')+
  scale_y_log10(labels = dollar_format(prefix = "$"))+
  ggtitle('players are in high demand in their mid-20s', subtitle= 'valuation on a log scale, so differences \nbetween the age groups are significant')+
  theme_fivethirtyeight()
```


```{r}
#team rating overall, in the 11 years average 
top_20_overall_clubs <-player_n_laliga_table %>% 
  group_by(club) %>% 
  summarise(AverageRating = mean(Overall)) %>% 
  arrange(desc(AverageRating)) %>% 
  head(n=20) %>% 
  pull(club)

player_n_laliga_table %>% 
  filter(club %in% top_20_overall_clubs) %>% 
  mutate(top3 = ifelse(club %in% c('FC Barcelona', 'Real Madrid', 'Atlético Madrid'), 'Yes','No')) %>% 
  ggplot(aes(x= reorder(club,Overall), y = Overall, fill= top3))+
  geom_boxplot(color = 'black')+
  scale_fill_manual(values= c('lightgrey','green'))+
  ggtitle('The teams with the highest Overall Ratings', subtitle= 'the average ovarall rating of the 20 highest rated teams in the game')+
  coord_flip()+
  theme_fivethirtyeight()+
  theme(legend.position= 'none')
  
#top_20_overall_clubs
```

```{r}
##teams with the most elite players i.e.(players with a rating of >=85)
player_n_laliga_table %>% 
  mutate(ElitePlayers = ifelse(Overall >=85, 'Elite','Not Elite')) %>% 
  group_by(season, club, ElitePlayers) %>% 
  filter(ElitePlayers == 'Elite') %>% 
  summarize(NumberElitePlayers = n()) %>% 
  #filter(NumberElitePlayers >1) %>% 
  mutate(top3 = ifelse(club %in% c('FC Barcelona','Real Madrid','Atlético Madrid'), 'Yes','No')) %>% 
  arrange(desc(NumberElitePlayers)) %>% 
  ggplot(aes(x = reorder(club, NumberElitePlayers), y = NumberElitePlayers, fill= top3))+
  geom_col(color = 'black')+
  scale_fill_manual(values = c('lightgrey','blue'))+
  coord_flip()+
  facet_wrap(~season, scales = 'free_x')+
  scale_y_continuous(breaks = seq(1,12,1))+
  theme_fivethirtyeight()+
  theme(legend.position ='none')


```

```{r}
```


```{r}
require(scales)
player_n_laliga_table %>% 
  filter(season == 2017) %>% 
  select(Name, Nationality, Overall, Value_spread, Wage_spread) %>% 
  group_by(Value_spread) %>% 
  arrange(desc(Value_spread)) %>% 
  head(30) %>% 
  ungroup() %>% 
  ggplot(mapping = aes( x= Name, y = Value_spread, color = Nationality, fill = Nationality, alpha = Value_spread, size = Value_spread))+
  geom_bar( stat = 'identity')+
  coord_polar()+
  theme_minimal()+
  labs( x = 'Name', y = 'Value_spread', title = 'Highest Valued Players in 2017')+
  theme(plot.title = element_text(hjust = 0.3), legend.position = 'bottom')+
  scale_y_continuous(labels = comma)



```


```{r}
```


```{r}
#for the year 2017
player_n_laliga_table %>% 
  filter(season== 2017) %>% 
  select(season,Name, Nationality, Overall, Value_spread,Wage_spread) %>% 
  group_by(season,Overall) %>% 
  arrange(desc(Overall)) %>% 
 head(30) %>% 
  ggplot( mapping = aes(x=Name, y=Overall, color=Nationality, alpha=Overall, size= Overall))+
  geom_point()+
  coord_polar()+
  theme_minimal()+
  labs(x = 'Name', y ='Overall', title ='Overall Top Players for 2017')+
  theme(plot.title = element_text(hjust=0.5),legend.position ='bottom')+
  scale_y_continuous(labels = comma)
```


```{r}

```


```{r}
# drawing a world map with highlights
###############options(scipen=999)#to prevent scientific notation
value_data <- player_n_laliga_table %>%
  filter(season %in% c(2016,2017)) %>% 
  select(Name, Nationality, Value_spread) %>% 
  group_by(Nationality) %>% 
  summarize(count=n(),
            Avg_Value = mean(Value_spread)) %>% 
  arrange(desc(Avg_Value)) 

worldmap=map_data('world')

merged_data <- merge(x = worldmap, y = value_data, by.x='region',by.y='Nationality', all.x=TRUE) %>% 
  arrange(order)
  ggplot(data= merged_data, aes(x= long, y=lat, group=group))+
  geom_polygon(aes(fill = Avg_Value))+
  labs(fill = 'Average Values')
```


```{r}
```


```{r}
country_per_team_per_year <- player_n_laliga_table %>% 
  group_by(season,club) %>%
  count(Nationality) %>% 
  ungroup()

country_per_team_per_year
```

```{r}
country_per_team_per_year %>%
  
  filter(Nationality == 'Spain'& season == 2017) %>%
  mutate(top3 = ifelse(club %in% c('FC Barcelona', 'Real Madrid', 'Atlético Madrid'), 'Yes','No'))%>% 
  ggplot(aes(x = reorder(club,-n), y = n, fill = top3))+
  geom_bar(stat = 'identity', color= 'black')+
  scale_fill_manual(values= c('lightgrey','darkorange'))+
  coord_flip()+
  geom_text(aes(y = n +1, label = n ))+
  theme_fivethirtyeight()+
  theme(legend.position= 'none')+
  ggtitle('2017 season winner: Madrid')
  #facet_wrap(~season, scale = 'free_x')
  
```

```{r}
country_per_team_per_year %>%
  
  filter(Nationality == 'Spain'& season == 2016) %>%
  mutate(top3 = ifelse(club %in% c('FC Barcelona', 'Real Madrid', 'Atlético Madrid'), 'Yes','No'))%>% 
  ggplot(aes(x = reorder(club,-n), y = n, fill = top3))+
  geom_bar(stat = 'identity', color= 'black')+
  scale_fill_manual(values= c('lightgrey','darkgreen'))+
  coord_flip()+
  geom_text(aes(y = n +1, label = n ))+
  theme_fivethirtyeight()+
  theme(legend.position= 'none')+
  ggtitle("2016 season winner:Barca")
  #facet_wrap(~season, scale = 'free_x')

```
```{r}
country_per_team_per_year %>%
  
  filter(Nationality == 'Spain'& season == 2015) %>%
  mutate(top3 = ifelse(club %in% c('FC Barcelona', 'Real Madrid', 'Atlético Madrid'), 'Yes','No'))%>% 
  ggplot(aes(x = reorder(club,-n), y = n, fill = top3))+
  geom_bar(stat = 'identity', color= 'black')+
  scale_fill_manual(values= c('lightgrey','blue'))+
  coord_flip()+
  geom_text(aes(y = n +1, label = n ))+
  theme_fivethirtyeight()+
  theme(legend.position= 'none')+
  ggtitle("2015 season winner:Barca")
```


```{r}
country_per_team_per_year %>%
  
  filter(Nationality == 'Spain'& season == 2014) %>%
  mutate(top3 = ifelse(club %in% c('FC Barcelona', 'Real Madrid', 'Atlético Madrid'), 'Yes','No'))%>% 
  ggplot(aes(x = reorder(club,-n), y = n, fill = top3))+
  geom_bar(stat = 'identity', color= 'black')+
  scale_fill_manual(values= c('lightgrey','yellow'))+
  coord_flip()+
  geom_text(aes(y = n +1, label = n ))+
  theme_fivethirtyeight()+
  theme(legend.position= 'none')+
  ggtitle("2014 season winner:Atletico")
```


```{r}
country_per_team_per_year %>%
  
  filter(Nationality == 'Spain'& season == 2013) %>%
  mutate(top3 = ifelse(club %in% c('FC Barcelona', 'Real Madrid', 'Atlético Madrid'), 'Yes','No'))%>% 
  ggplot(aes(x = reorder(club,-n), y = n, fill = top3))+
  geom_bar(stat = 'identity', color= 'black')+
  scale_fill_manual(values= c('lightgrey','purple'))+
  coord_flip()+
  geom_text(aes(y = n +1, label = n ))+
  theme_fivethirtyeight()+
  theme(legend.position= 'none')+
  ggtitle("2013 season winner:Barca")
```


```{r}
country_per_team_per_year %>%
  
  filter(Nationality == 'Spain'& season == 2012) %>%
  mutate(top3 = ifelse(club %in% c('FC Barcelona', 'Real Madrid', 'Atlético Madrid'), 'Yes','No'))%>% 
  ggplot(aes(x = reorder(club,-n), y = n, fill = top3))+
  geom_bar(stat = 'identity', color= 'black')+
  scale_fill_manual(values= c('lightgrey','lightgreen'))+
  coord_flip()+
  geom_text(aes(y = n +1, label = n ))+
  theme_fivethirtyeight()+
  theme(legend.position= 'none')+
  ggtitle("2012 season winner:madrid")
```


```{r}
```


```{r}
```


```{r}
```

```{r}
#library(gganimate)
la_liga_table %>% 
  group_by(season) %>% 
  mutate(rank = order(order(points, decreasing = TRUE))) %>% 
  select(season, club,points, rank ) %>% 
  ungroup() %>% 
  filter(club %in% c('Real Madrid','FC Barcelona','Atlético Madrid','Valencia CF','Athletic Club de Bilbao','Real Sociedad','Deportivo Alavés')) %>% 
  ggplot(aes(x=season, y=rank, group=club, color=club))+
  geom_line()+
  scale_y_continuous(breaks = seq(1,21,1))+
  scale_x_continuous(breaks = seq(1970,2018,1))+
  scale_color_viridis_d()+
  labs(x = "Season", y = "Position") +
  theme(axis.text.x = element_text(angle = 90), legend.position = "top")+ transition_reveal(season)

```


```{r}
#got the new version of R
###R.Version()
```


```{r}


```

##########Try to make a cool looking table#######

########install libraries to make the cool table ##

```{r}


library(gridExtra)
library(grid)
```

```{r}
#bring in the la_liga table dataset 
la_liga_2.0 <- read_csv('data/la_liga_table.csv') %>% 
  group_by(season) %>% 
  mutate (pos = order(order(points, decreasing = TRUE))) %>%
  ungroup()
```


```{r}

```
* Using `dplyr` helper functions, including:
    * `starts_with()`
    * `ends_with()`
    * `contains()`
    * `one_of()` if you need to specify columns as a string
    * `everything()`


```{r}
library(gt)

#remotes::install_github("rstudio/gt")
o_10 <- la_liga_2.0 %>% 
  filter(season == 2010) %>% 
  arrange(pos) %>% 
  select(season,pos,Team = club,Played = total_matches,HW = home_win, HL = home_loss,HG = home_goals, 
         AW = away_win, AL = away_loss, AG = away_goals, 
         Wins = matches_won, Draws = matches_drawn, Losses = matches_lost,
         For = goals_scored,Against = goals_conceded,
        `Goal Diff` = goal_difference, Points = points)
         
```





```{r}
la_liga_2.0 %>% 
  filter(season == 1990) %>% 
  arrange(pos)
```


```{r}
lame <-gt(o_10) 

 o_10 %>%
  gt(rowname_col = "season") %>%
   
  tab_spanner(
    label = "HOME",
    columns = vars(HW, HL, HG)
  ) %>%
  tab_spanner(
    label = "AWAY",
    columns = vars(AW, AL, AG)
  ) %>% 
   tab_spanner(
     label = "TOTAL",
     columns = vars(Wins,Draws,Losses,For,
                   Against,`Goal Diff`,Points)
   )%>%
  tab_style(
    style = list(
      cell_fill(color = "red"),
      cell_text(color = "black")
      ),
    locations = cells_body(
      rows = pos >= 18)
  ) %>% 
   tab_style(
     style= list(
       cell_fill(color = 'lightgreen'),
       cell_text(color = 'black')
       
     ),
     locations = cells_body(
       rows = pos == 1)
     )
 
   
```

```{r}
```


```{r}
order <- la_liga_2.0 %>% 
  arrange(pos) %>% 
  select(season,pos,Team = club,Played = total_matches,HW = home_win, HL = home_loss,HG = home_goals, 
         AW = away_win, AL = away_loss, AG = away_goals, 
         Wins = matches_won, Draws = matches_drawn, Losses = matches_lost,
         For = goals_scored,Against = goals_conceded,
        `Goal Diff` = goal_difference, Points = points)
  
order <- gt(order)
```


```{r}
#lame <-gt(o_10) 

 #a <- order %>%
  #gt(rowname_col = "season") %>%
  order %>%
  tab_spanner(
    label = "HOME",
    columns = vars(HW, HL, HG)
  ) %>%
  tab_spanner(
    label = "AWAY",
    columns = vars(AW, AL, AG)
  ) %>% 
   tab_spanner(
     label = "TOTAL",
     columns = vars(Wins,Draws,Losses,For,
                   Against,`Goal Diff`,Points)
   )%>%
  tab_style(
    style = list(
      cell_fill(color = "red"),
      cell_text(color = "black")
      ),
    locations = cells_body(
      rows = pos >= 18)
  ) %>% 
   tab_style(
     style= list(
       cell_fill(color = 'lightgreen'),
       cell_text(color = 'black')
       
     ),
     locations = cells_body(
       rows = pos == 1)
     )
```


```{r}
# trial.df <- as.data.frame(trial)
# str(trial.df)

```


```{r}
order %>% 
  cells_column_labels()
```


```{r}
order %>% 
  select(season)

```




```{r}
la_liga_2.0 <- data.frame(la_liga_2.0)
```


```{r}

team <- "club"
matches <- c("matches_won","matches_drawn","matches_lost")

  highchart() %>% 
  hc_title(text = 'Results per Team') %>% 
  hc_xAxis(categories = la_liga_2.0[,'club'],
           title = 'club') %>% 
  hc_add_series(name = 'Wins',
                #type = 'column',
                data = la_liga_2.0[,matches[1]]) %>% 
  hc_add_series(name = 'Draws',
                #type = 'column',
                data = la_liga_2.0[,matches[2]]) %>% 
  hc_add_series(name = 'Losses',
                #type = 'column',
                data = la_liga_2.0[,matches[3]]) %>% 
    hc_chart(type = "column") %>% 
    hc_colors(c('#90ed7d', '#cccccc', '#ff3333')) %>%
    hc_tooltip(crosshairs = TRUE, shared = TRUE)
```

```{r}


  # 
  #   #plot
  #   highchart() %>%
  #     hc_title(text = "Results per Team") %>%
  #     hc_xAxis(categories = footy_all_result[, Team]) %>%
  #     hc_add_series(name = 'Wins', 
  #                   type = 'column', 
  #                   data = footy_all_result[, Wins])   %>%
  #     hc_add_series(name = 'Draws', 
  #                   type = 'column',
  #                   data = footy_all_result[, Draws])  %>%
  #     hc_add_series(name = 'Losses', 
  #                   type = 'column',
  #                   data = footy_all_result[, Losses]) %>%
  #     hc_colors(c('#90ed7d', '#cccccc', '#ff3333')) %>%
  #     hc_tooltip(crosshairs = TRUE, shared = TRUE)
  #   
  # })


 
  #seen like you have to do data.frame() in order for highchart() to work  
  chart <- data.frame(la_liga_2.0) %>% 
  filter(season == 2017)
  
  #team <- "club"
  matches <- c("goals_scored","goals_conceded","goal_difference")
  
  highchart() %>% 
    hc_title(text = paste('Goals per Team:')) %>% 
    hc_xAxis(categories = chart[,'club'],
             title = 'club') %>% 
    hc_add_series(name = 'Goals Scored',
                  type = 'column',
                  data = chart[,matches[1]]) %>% 
    hc_add_series(name = 'Goals Conceded',
                  type = 'column',
                  data = chart[,matches[2]]) %>% 
    hc_add_series(name = 'Goal Difference',
                  type = 'spline',
                  data = chart[,matches[3]]) %>% 
    #hc_chart(type = "column") %>% 
    hc_colors(c('#1aadce', '##2f7ed8', '#ff3333')) %>%
    hc_tooltip(crosshairs = TRUE, shared = TRUE)%>% 
    hc_yAxis(title = list(text = "Games Played"))
  

```

```{r}
sample_data <- data.frame(
  "Countries" = c(
    "United Kingdom","France","Saudi Arabia","Egypt","Germany","China","Slovakia","Canada","Estonia","Ireland"
  ),
  "Business" =  c(8, 6, 7, 8, 9, 7, 9, 7, 9, 9),
  "Overlay" = c(22, 28, 11, 19, 11, 39, 22, 10, 30, 7),
  "Personal" = c(19, 21, 21, 20, 19, 19, 21, 21, 20, 20),
  "Teleconference" = c(9, 29, 21, 44, 59, 11, 53, 16, 49, 36),
  "Unclassified" = c(42, 48, 50, 45, 49, 40, 42, 47, 48, 44)#,
  #stringsAsFactors = F
)
categories_column <- "Countries"
measure_columns <- c("Business","Overlay","Personal","Teleconference","Unclassified")
```


```{r}
base_highchart <- highchart() %>%
  hc_xAxis(categories = sample_data[,categories_column],
           title = categories_column) %>%
  hc_add_series(name = measure_columns[1],
                data = sample_data[,measure_columns[1]]) %>%
  hc_add_series(name = measure_columns[2],
                data = sample_data[,measure_columns[2]]) %>%
  hc_add_series(name = measure_columns[3],
                data = sample_data[,measure_columns[3]]) %>%
  hc_add_series(name = measure_columns[4],
                data = sample_data[,measure_columns[4]]) %>%
  hc_add_series(name = measure_columns[5],
                data = sample_data[,measure_columns[5]])

base_highchart %>% hc_chart(type = "column")
```


```{r}
survey18 %>% 
  count(YearsCoding, Employment) %>% 
  hchart('line', hcaes(x = 'YearsCoding', y = 'n', group = "Employment"))
```


```{r}
la_liga_2.0 %>%
  
  count(season,club,pos) %>% 
  hchart('line', hcaes(x= 'season', y = 'pos', group = 'club')) 
  
```


```{r}

```

```{r}
la_liga_2.0
```


```{r}
la_liga_2.0 %>%
  group_by(season, club) %>% 
  filter(pos == 1) %>%
  ungroup() %>%
  group_by(club) %>% 
  count() %>% 
  rename(champ = n) %>% 
  arrange(desc(champ)) %>% 
  ungroup() %>% 
  hchart('treemap', hcaes(x = 'club', value = 'champ', color = 'champ')) %>% 
   hc_colorAxis(
    minColor = "gray",
    maxColor = "yellow"
  )
  
  
```


```{r}


```


```{r}


```

```{r}
#bring in the player data
with_players <-read_csv('data/fifa_player_data_07-17.csv') %>% 
  rename(season = Year, club = Club) %>% 
  filter(season >= 2007) %>% 
  inner_join(la_liga_2.0, by = c('club', 'season')) %>% 
  select(season, club, everything())
```


```{r}
view(with_players)
```


```{r}

dim(with_players)

```


```{r}
with_players
```


```{r}
with_players %>% 
  group_by(season, club, Nationality) %>% 
  count() %>% 
  rename(national_variance = n)
```


```{r}
work_df <- with_players %>% 
  select(season,club,Name)
work_df
```


```{r}

```


```{r}
find_new_players <- function ( year, team) {
  

    A <- work_df %>% 
    filter(club == team & season == year) %>% 
    pull(Name)
  
    B <- work_df %>% 
    filter(club == team & season == year -1) %>% 
    pull(Name)
    
    difference <-setdiff(A, B)
   
 
 return (difference)
}

```

```{r}
find_new_players(year = 2007, team = 'Real Madrid')
```

```{r}
A <- work_df %>% 
  filter(club == 'Real Madrid' & season == 2016) %>% 
  pull(Name)
A

```

```{r}
B <- work_df %>% 
  filter(club == 'Real Madrid' & (season == 2016-1)) %>% 
  pull(Name)
B

```

```{r}
setdiff(B,A)
```

```{r}
with_players
```
```{r}
just_for_sample <-with_players %>% 
  filter(season == 2016 & club == 'Real Madrid') %>% 
  arrange(desc(Overall))
  
just_for_sample 
```

```{r}
highchart() %>% 
  hc_chart(polar = TRUE) %>% 
  hc_title(text = 'Player Rating',
           style = list(fontWeight = 'bold', fontSize = '20px', align = 'center')) %>% 
  hc_subtitle(text = '85 or higher is considered Elite Player',
              stype = list(fontWeight = 'bold'), align = 'center') %>% 
  hc_xAxis(categories = just_for_sample$Name, style = list(fontWeight = 'bold')) %>% 
  hc_legend(enabled = FALSE) %>% 
  #hc_add_theme(hc_theme_tufte()) %>%
  hc_series(
    list(
      name = "Bars",
      data = just_for_sample$Overall,
      colorByPoint = TRUE,
      type = "column",
      colors = ifelse(just_for_sample$Overall >= 85, 'purple','light')),
    list(
      name = 'Overall Rating',
      data = just_for_sample$Overall,
      pointPlacement = 'on',
      type = 'line'
    )
  )
  
```


```{r}

```


```{r}

```

```{r}

```

```{r}

```


```{r}
sunburst_chart <-with_players %>% 
  filter(season == 2016 & club == 'Real Madrid') %>% 
  arrange(desc(Overall)) 
sunburst_chart
```


```{r}
# Install package from CRAN:
#install.packages("collapsibleTree")
#library(collapsibleTree)

```


```{r}

```


```{r}
collapsibleTree(
  sunburst_chart,
  hierarchy = c("Nationality","Name","Age","Position"),
  width = 700,
  zoomable = TRUE
  
)
```


```{r}




```


```{r}
#install.packages('d3Tree')
#library(d3Tree)
random_tree  <- sunburst_chart %>% 
  group_by(club,Nationality, Name, Age,Position) %>% 
  count()
d3tree(list(root = df2tree(rootname = 'Your selected Team', struct = as.data.frame(random_tree)),
            layout = 'collapse'))

```

```{r}
#library(treemap)
#install.packages("sunburstR")
#library(sunburstR)

  

```


```{r}
#library(data.table)



```


```{r}
# Libraries
#library(ggraph)
#library(igraph)

 


```


```{r}
this_one <-with_players %>% 
  filter(season == 2007) %>% 
  group_by(season, club) %>% 
  mutate (Ov_average = mean(Overall))
this_one

overall_average <-this_one %>% 
  group_by(season,club) %>% 
  summarize(overall_average = unique(mean(Overall))) %>% 
  ungroup()
```


```{r}
# plotline <- list(
#   color = "red", value = mean(this_one$Age), width = 2, zIndex = 5
# )
# 
# hcboxplot(x = this_one$Age, var = this_one$club,
#           name = "Age", color = "#2980b9") %>% 
#   hc_chart(type = "column") %>%
#   hc_yAxis(plotLines = list(plotline))
  
   # to put box vertical
```


```{r}
highchart() %>% 
  hc_add_series_boxplot(x = this_one$Age, by = this_one$club, name = "Age") %>%
  #hc_yAxis(plotLines = list(plotline)) %>% 
  hc_add_series_boxplot(x = this_one$Overall, by = this_one$club, name = 'Overall Rating')
  



```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

